[project]
name = "examen-bentoml"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "bentoml>=1.4.22",
    "pandas>=2.3.2",
    "scikit-learn>=1.7.1",
]

[dependency-groups]
dev = [
    "pytest>=8.4.1",
]
